
import { Rule } from "publicodes";

export type DottedName = 
| "numérique . internet . diminuer"
| "numérique . internet . empreinte réduite"
| "numérique . internet . durée journalière . réduction"
| "numérique . usage responsable"
| "intensité électricité"
| "jours par an"
| "serveur"
| "serveur . puissance"
| "serveur . puissance par utilisateur"
| "serveur . nombre d'utilisateurs par serveur"
| "serveur . PUE mails"
| "serveur . PUE streaming"
| "serveur . capacité"
| "serveur . construction"
| "serveur . durée de vie"
| "serveur . puissance en mode actif"
| "firewall"
| "firewall . construction"
| "firewall . durée de vie"
| "switch"
| "switch . construction"
| "switch . durée de vie"
| "routeur"
| "routeur . construction"
| "routeur . durée de vie"
| "stockage"
| "stockage . construction"
| "stockage . durée de vie"
| "stockage . puissance en mode actif"
| "équipements support"
| "équipements support . construction"
| "équipements support . durée de vie"
| "construction data center"
| "construction data center . serveur"
| "construction data center . serveur . facteur d'allocation"
| "construction data center . firewall"
| "construction data center . firewall . facteur d'allocation"
| "construction data center . switch"
| "construction data center . switch . facteur d'allocation"
| "construction data center . routeur"
| "construction data center . routeur . facteur d'allocation"
| "construction data center . stockage"
| "construction data center . stockage . facteur d'allocation"
| "construction data center . équipements support"
| "construction data center . équipements support . facteur d'allocation"
| "usage data center"
| "usage data center . consommation électricité"
| "usage data center . région"
| "usage data center . facteur électricité"
| "email"
| "email . taille"
| "email . taille en Go"
| "email . destinataires"
| "email . durée stockage mail"
| "email . redondances sauvegarde émetteur"
| "email . redondances sauvegarde récepteur"
| "email . taux moyen de remplissage du stockage"
| "email . nombre de mails envoyés et reçus par jour et par personne"
| "email . terminaux"
| "email . terminaux . construction"
| "email . appareil"
| "email . appareil . moyenne utilisation ordinateur et écran"
| "email . appareil . moyenne utilisation ordinateur portable"
| "email . appareil . moyenne utilisation tablette"
| "email . appareil . moyenne utilisation smartphone"
| "email . appareil . durée totale sollicitation"
| "email . terminaux . temps écriture"
| "email . terminaux . temps écriture en heure"
| "email . terminaux . pourcentage lecture"
| "email . terminaux . temps lecture récepteur"
| "email . terminaux . temps lecture total"
| "email . terminaux . temps lecture en heure"
| "email . terminaux . usage"
| "email . transmission"
| "email . transmission . émetteur"
| "email . transmission . émetteur . réseau"
| "email . transmission . récepteur"
| "email . transmission . récepteur . réseau"
| "email . transmission . redondances sauvegarde"
| "email . transmission . redondances sauvegarde . facteur réseau"
| "email . transmission . redondances sauvegarde . réseau"
| "email . data center"
| "email . data center . construction"
| "email . data center . construction . émetteur"
| "email . data center . construction . émetteur . facteur d'allocation serveur"
| "email . data center . construction . émetteur . facteur d'allocation stockage"
| "email . data center . construction . émetteur . facteur d'allocation stockage . taille mails"
| "email . data center . construction . émetteur . facteur d'allocation stockage . ratio total"
| "email . data center . construction . récepteur"
| "email . data center . usage"
| "email . data center . usage . émetteur"
| "email . data center . usage . émetteur . consommation électricité réelle"
| "email . data center . usage . émetteur . consommation électricité"
| "email . data center . usage . émetteur . consommation électricité . consommation serveur par mail"
| "email . data center . usage . émetteur . consommation électricité . consommation serveur stockage"
| "email . data center . usage . récepteur"
| "fichier"
| "fichier . taille"
| "fichier . transmission"
| "fichier . transmission . réseau"
| "fichier . data center"
| "fichier . data center . construction"
| "fichier . data center . facteur allocation serveur"
| "fichier . data center . usage"
| "fichier . data center . usage . consommation électricité"
| "fichier . data center . usage . électricité par Go en Wh"
| "fichier . data center . usage . électricité par Go"
| "électricité"
| "électricité . FE France"
| "électricité . FE Europe"
| "électricité . FE Chine"
| "électricité . FE USA"
| "recherche web"
| "recherche web . temps de saisie"
| "recherche web . temps de saisie en heure"
| "recherche web . taille de la requete"
| "recherche web . taille de la requete en Mo"
| "recherche web . taille de la requete en Go"
| "recherche web . taille de la page"
| "recherche web . taille de la page en Mo"
| "recherche web . taille de la page en Go"
| "recherche web . temps de consultation"
| "recherche web . temps de consultation en heure"
| "recherche web . nombre de pages de résultats lues"
| "recherche web . terminaux"
| "recherche web . terminaux . construction"
| "recherche web . appareil"
| "recherche web . appareil . moyenne utilisation ordinateur et écran"
| "recherche web . appareil . moyenne utilisation ordinateur portable"
| "recherche web . appareil . moyenne utilisation tablette"
| "recherche web . appareil . moyenne utilisation smartphone"
| "recherche web . appareil . durée totale sollicitation"
| "recherche web . terminaux . usage"
| "recherche web . transmission"
| "recherche web . transmission . réseau"
| "recherche web . data center"
| "recherche web . data center . allocation serveur par Mo"
| "recherche web . data center . facteur d'allocation serveur"
| "recherche web . data center . construction"
| "recherche web . data center . usage"
| "recherche web . data center . usage . consommation électricité"
| "recherche web . data center . usage . consommation totale serveur"
| "recherche web . data center . usage . consommation annuelle serveur"
| "streaming"
| "streaming . qualité"
| "streaming . qualité . facteur qualité"
| "streaming . durée"
| "streaming . durée en heure"
| "streaming . taille"
| "streaming . terminaux"
| "streaming . terminaux . construction"
| "streaming . appareil"
| "streaming . appareil . moyenne utilisation ordinateur et écran"
| "streaming . appareil . moyenne utilisation ordinateur portable"
| "streaming . appareil . moyenne utilisation tablette"
| "streaming . appareil . moyenne utilisation smartphone"
| "streaming . appareil . moyenne utilisation TV"
| "streaming . terminaux . usage"
| "streaming . transmission"
| "streaming . transmission . réseau"
| "streaming . data center"
| "streaming . data center . construction"
| "streaming . data center . construction . facteur d'allocation serveur"
| "streaming . data center . usage"
| "streaming . data center . usage . consommation électricité"
| "streaming . data center . usage . électricité par Go en Wh"
| "streaming . data center . usage . électricité par Go"
| "streaming . data center . nombre de serveurs"
| "streaming . data center . volume total de transfert de données"
| "streaming . data center . puissance installée avant PUE"
| "streaming . électricité directe consommée par an"
| "streaming . électricité indirecte consommée par an"
| "streaming . consommation de donnée moyenne par heure de visionnage"
| "streaming . nombre d'utilisateurs par an"
| "streaming . nombre d'heures de visionnage par an"
| "construction réelle"
| "construction réelle . moyenne"
| "construction réelle . smartphone"
| "construction réelle . tablette"
| "construction réelle . ordinateur portable"
| "construction réelle . TV"
| "construction réelle . ordinateur et écran"
| "usage réel"
| "usage réel . facteur électricité"
| "usage réel . région"
| "usage réel . consommation électricité"
| "usage réel . consommation électricité par heure"
| "usage réel . consommation en mode actif moyenne"
| "appareil par défaut"
| "durée en heure par défaut"
| "moyenne utilisation ordinateur et écran par défaut"
| "moyenne utilisation ordinateur portable par défaut"
| "moyenne utilisation tablette par défaut"
| "moyenne utilisation smartphone par défaut"
| "moyenne utilisation TV par défaut"
| "smartphone"
| "smartphone . construction"
| "smartphone . durée d'usage"
| "smartphone . durée de vie"
| "smartphone . durée de vie par défaut"
| "smartphone . profil utilisation"
| "smartphone . profil utilisation par défaut"
| "smartphone . consommation en mode actif"
| "tablette"
| "tablette . construction"
| "tablette . durée d'usage"
| "tablette . durée de vie"
| "tablette . durée de vie par défaut"
| "tablette . profil utilisation"
| "tablette . profil utilisation par défaut"
| "tablette . consommation en mode actif"
| "ordinateur portable"
| "ordinateur portable . construction"
| "ordinateur portable . durée d'usage"
| "ordinateur portable . durée de vie"
| "ordinateur portable . durée de vie par défaut"
| "ordinateur portable . profil utilisation"
| "ordinateur portable . profil utilisation par défaut"
| "ordinateur portable . consommation en mode actif"
| "TV"
| "TV . construction"
| "TV . durée d'usage"
| "TV . durée de vie"
| "TV . durée de vie par défaut"
| "TV . profil utilisation"
| "TV . profil utilisation par défaut"
| "TV . consommation en mode actif"
| "ordinateur fixe"
| "ordinateur fixe . construction"
| "ordinateur fixe . durée de vie par défaut"
| "ordinateur fixe . consommation en mode actif"
| "écran"
| "écran . construction"
| "écran . durée de vie par défaut"
| "écran . consommation en mode actif"
| "ordinateur et écran"
| "ordinateur et écran . construction"
| "ordinateur et écran . durée d'usage"
| "ordinateur et écran . durée de vie"
| "ordinateur et écran . durée de vie par défaut"
| "ordinateur et écran . profil utilisation"
| "ordinateur et écran . profil utilisation par défaut"
| "ordinateur et écran . consommation en mode actif"
| "transmission par défaut"
| "transmission par défaut . taille par défaut"
| "transmission par défaut . réseau par défaut"
| "transmission par défaut . facteur réseau"
| "transmission par défaut . facteur réseau fixe FR"
| "transmission par défaut . facteur réseau mobile FR"
| "transmission par défaut . facteur réseau fixe EU"
| "transmission par défaut . facteur réseau mobile EU"
| "transmission par défaut . facteur réseau fixe FR hors box"
| "transmission par défaut . facteur réseau fixe EU hors box"
| "visio"
| "visio . qualité"
| "visio . qualité . facteur qualité"
| "visio . durée"
| "visio . durée en heure"
| "visio . taille"
| "visio . emplacements"
| "visio . terminaux"
| "visio . appareil . durée totale sollicitation"
| "visio . terminaux . construction"
| "visio . appareil"
| "visio . appareil . moyenne utilisation ordinateur et écran"
| "visio . appareil . moyenne utilisation ordinateur portable"
| "visio . appareil . moyenne utilisation tablette"
| "visio . appareil . moyenne utilisation smartphone"
| "visio . appareil . moyenne utilisation TV"
| "visio . terminaux . usage"
| "visio . transmission"
| "visio . transmission . réseau"
| "visio . data center"
| "visio . data center . construction"
| "visio . data center . facteur allocation serveur"
| "visio . data center . usage"
| "visio . data center . usage . consommation électricité"
| "visio . data center . usage . électricité par Go"
| "numérique"
| "numérique . internet"
| "numérique . internet . consommation horaire"
| "numérique . internet . empreinte horaire"
| "numérique . internet . durée journalière"
| "numérique . préservation"
| "numérique . préservation . faible"
| "numérique . préservation . achat neuf"
| "numérique . préservation . moyen"
| "numérique . préservation . maximum"
| "numérique . coefficient préservation"
| "numérique . appareils"
| "numérique . appareils . téléphone . présent"
| "numérique . appareils . téléphone"
| "numérique . appareils . téléphone . type"
| "numérique . appareils . téléphone . durée"
| "numérique . appareils . téléphone . impact"
| "numérique . appareils . téléphone . type . téléphone basique"
| "numérique . appareils . téléphone . type . smartphone classique"
| "numérique . appareils . téléphone . type . smartphone haut de gamme"
| "numérique . appareils . appareil photo . présent"
| "numérique . appareils . appareil photo . durée"
| "numérique . appareils . appareil photo"
| "numérique . appareils . home cinéma . présent"
| "numérique . appareils . home cinéma . durée"
| "numérique . appareils . home cinéma"
| "numérique . appareils . ordinateur portable . présent"
| "numérique . appareils . ordinateur portable . durée"
| "numérique . appareils . ordinateur portable"
| "numérique . appareils . ordinateur fixe . présent"
| "numérique . appareils . ordinateur fixe . durée"
| "numérique . appareils . ordinateur fixe"
| "numérique . appareils . ordinateur fixe . empreinte"
| "numérique . appareils . ordinateur fixe . écran"
| "numérique . appareils . tablette . présent"
| "numérique . appareils . tablette . durée"
| "numérique . appareils . tablette"
| "numérique . appareils . TV . présent"
| "numérique . appareils . TV . durée"
| "numérique . appareils . TV"
| "numérique . appareils . vidéoprojecteur . présent"
| "numérique . appareils . vidéoprojecteur . durée"
| "numérique . appareils . vidéoprojecteur"
| "numérique . appareils . enceinte bluetooth . présent"
| "numérique . appareils . enceinte bluetooth . durée"
| "numérique . appareils . enceinte bluetooth"
| "numérique . appareils . enceinte vocale . présent"
| "numérique . appareils . enceinte vocale . durée"
| "numérique . appareils . enceinte vocale"
| "numérique . appareils . montre connectée . présent"
| "numérique . appareils . montre connectée . durée"
| "numérique . appareils . montre connectée"
| "numérique . appareils . console de salon . présent"
| "numérique . appareils . console de salon . durée"
| "numérique . appareils . console de salon"
| "numérique . appareils . console portable . présent"
| "numérique . appareils . console portable . durée"
| "numérique . appareils . console portable"

declare let rules: Record<DottedName, Rule>

export default rules;
